language: php

php:
    - 7.3

services:
    - mysql

before_script:
    - cp .env.travis .env
    - mysql -u root -e 'create database laravel;'
    - composer self-update
    - composer install --dev --prefer-source --no-interaction
    - php artisan key:generate
    - php artisan migrate:install --env=testing --no-interaction
    - composer dump-autoload
    - sudo chgrp -R www-data storage bootstrap/cache
    - sudo chmod -R ug+rwx storage bootstrap/cache
    - php artisan migrate
    - php artisan db:seed

deploy:
    provider: heroku
    api_key: 6019b092-8156-4195-b50d-2cbca91c58df
    app: imagemanagerv
